name: Build and test
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 17
          - os: windows-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - name: Build and test blocksJVM
      shell: bash
      run: sbt "project blocksJVM ; clean ; test"
    - name: Build and test blocksJS
      shell: bash
      run: sbt "project blocksJS ; clean ; test"
    - name: Build and test blocksUpickleJVM
      shell: bash
      run: sbt "project blocksUpickleJVM ; clean ; test"
    - name: Build and test blocksUpickleJS
      shell: bash
      run: sbt "project blocksUpickleJS ; clean ; test"
